42BV/ui

package.json
packages/core/Avatar/package.json
packages/core/Breadcrumbs/package.json
packages/core/Button/package.json
packages/core/ConfirmButton/package.json
packages/core/ContentState/package.json
packages/core/FlashMessage/package.json
packages/core/Icon/package.json
packages/core/InfoBadge/package.json
packages/core/LoadingPage/package.json
packages/core/MoreOrLess/package.json
packages/core/NavigationItem/package.json
packages/core/Pagination/package.json
packages/core/Pagination/src/Pagination.tsx
packages/core/Spinner/package.json
packages/core/SubmitButton/package.json
packages/core/Tag/package.json

Also removed unnecessary `@ts-ignore` from Pagination, which triggered an eslint error in the new setup.
Fixes #31 and fixes #30.

improvement: update scripts

---

packages/core/ProgressStepper/CHANGELOG.md
packages/core/ProgressStepper/README.md
packages/core/ProgressStepper/example/ProgressStepper.stories.tsx
packages/core/ProgressStepper/example/ProgressStepperExample.stories.tsx
packages/core/ProgressStepper/jest.config.js
packages/core/ProgressStepper/package.json
packages/core/ProgressStepper/src/ProgressStepper.scss
packages/core/ProgressStepper/src/ProgressStepper.tsx
packages/core/ProgressStepper/test/ProgressStepper.test.tsx
packages/core/ProgressStepper/test/__snapshots__/ProgressStepper.test.tsx.snap
packages/core/ProgressStepper/tsconfig.json
packages/core/_bundle/README.md
packages/core/_bundle/package.json
packages/core/_bundle/src/index.ts
packages/core/_bundle/src/main.scss
packages/core/_bundle/test/__snapshots__/index.test.ts.snap

It allows the user to indicate at which stage in a form wizard the
user currently is.
Closes: #26

Feature: added a `ProgressStepper` component.

---

.size-snapshot.json
.travis.yml
package.json
src/core/AsyncContent/AsyncContent.stories.tsx
src/core/AsyncContent/AsyncContent.test.tsx
src/core/AsyncContent/AsyncContent.tsx
src/core/AsyncContent/__snapshots__/AsyncContent.test.tsx.snap
src/core/ContentState/ContentState.scss
src/core/ContentState/ContentState.stories.tsx
src/core/ContentState/ContentState.test.tsx
src/core/ContentState/ContentState.tsx
src/core/ContentState/__snapshots__/ContentState.test.tsx.snap
src/index.ts
yarn.lock

Feature: AsyncContent

---

src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.stories.tsx
src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.test.tsx
src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.tsx
src/form/CheckboxMultipleSelect/__snapshots__/CheckboxMultipleSelect.test.tsx.snap
src/form/ModalPicker/multiple/ModalPickerMultiple.test.tsx
src/form/ModalPicker/multiple/ModalPickerMultiple.tsx
src/form/ModalPicker/single/ModalPickerSingle.test.tsx
src/form/ModalPicker/single/ModalPickerSingle.tsx
src/form/ModalPicker/single/__snapshots__/ModalPickerSingle.test.tsx.snap
src/form/ModalPicker/types.ts
src/form/Select/Select.test.tsx
src/form/Typeahead/multiple/TypeaheadMultiple.tsx
src/form/Typeahead/single/TypeaheadSingle.tsx
src/form/ValuePicker/ValuePicker.stories.tsx
src/form/ValuePicker/ValuePicker.test.tsx
src/form/ValuePicker/ValuePicker.tsx
src/form/ValuePicker/__snapshots__/ValuePicker.test.tsx.snap
src/form/types.ts
src/index.ts
src/test/fixtures.ts
src/test/utils.tsx

Feature: ValuePicker and CheckboxMultipleSelect
Added the `ValuePicker` component, which is an abstraction which automatically
selects the best component to use when the user has to select a value
from a pre-defined list.
This is the decision matrix:
```
| multiple | items <= 10             | items > 10
| true     | CheckboxMultipleSelect  | ModalPickerMultiple
| false    | Select                  | ModalPickerSingle
```
`ValuePicker` start in a booting state in which a spinner is shown.
During the booting state it will call `FetchOptionsCallback` and ask
for a `Page` of size `1` so it can get the `totalElements`.
Refactored common typings to the `src/form/types.ts` so they can be
re-used, and to make the `ValuePicker` work.
Changed the  `FetchOptionsCallback` callback so it accepts a …

Feature: value picker

---

src/form/Checkbox/Checkbox.stories.tsx
src/form/Checkbox/Checkbox.test.tsx
src/form/Checkbox/Checkbox.tsx
src/form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
src/form/FormExample.stories.tsx
src/index.ts

The `Checkbox` can be used when the value is a boolean.

feat: added Checkbox form component.

---

src/core/Icon/Icon.stories.tsx
src/core/Icon/Icon.test.tsx
src/core/Icon/Icon.tsx
src/core/Icon/__snapshots__/Icon.test.tsx.snap

improvement: `Icon` component now supports optional font size property.

---

src/core/SearchInput/SearchInput.stories.tsx
src/core/SearchInput/SearchInput.test.tsx
src/core/SearchInput/SearchInput.tsx
src/core/SearchInput/__snapshots__/SearchInput.test.tsx.snap

Adding a placeholder on SearchInput worked, but it was not documented properly, so people might not understand they can use it.
Closes #318

Added placeholder to SearchInput

---

src/form/DateTimeInput/DateTimeInput.test.tsx
src/form/DateTimeInput/__snapshots__/DateTimeInput.test.tsx.snap

Code coverage for DateTimeInput was not 100%.
Added a test to check ui when there's a format error.

Improve DateTimeInput test coverage

---

src/core/Button/Button.tsx
src/form/AutoSave/AutoSave.test.tsx
src/form/AutoSave/AutoSave.tsx
src/form/AutoSave/__snapshots__/AutoSave.test.tsx.snap
src/form/AutoSave/useActive.ts
src/form/AutoSave/usePromise.ts
src/form/FormButton/FormButton.test.tsx
src/form/FormButton/FormButton.tsx
src/form/FormButton/__snapshots__/FormButton.test.tsx.snap
src/main.scss
src/table/EpicTable/cells/EpicForm/EpicForm.scss
src/table/EpicTable/cells/EpicForm/EpicForm.test.tsx
src/table/EpicTable/cells/EpicForm/EpicForm.tsx
src/table/EpicTable/cells/EpicForm/__snapshots__/EpicForm.test.tsx.snap
src/table/EpicTable/cells/EpicFormCell/EpicFormCell.test.tsx
src/table/EpicTable/cells/EpicFormCell/EpicFormCell.tsx
src/table/EpicTable/cells/EpicFormCell/__snapshots__/EpicFormCell.test.tsx.snap
src/table/FormTable/FormTable.stories.tsx
storybook/preview.js

In some cases you might want to display an EpicTable with form fields
to easily change a bunch of data in one batch.
Added EpicForm component which wraps around final-form Form component.
Includes possibility to automatically submit on change.
Added FormButton to submit or reset a Form externally.
Closes #357
Closes #400

improvement: form in EpicTable

---

src/core/OpenCloseModal/OpenCloseModal.stories.tsx
src/core/OpenCloseModal/OpenCloseModal.test.tsx
src/core/OpenCloseModal/OpenCloseModal.tsx
src/core/OpenCloseModal/__snapshots__/OpenCloseModal.test.tsx.snap

This way uses of the `OpenCloseModal` can show their users that
something is happening for when saving takes a while.
Closes: #420

improvement: OpenCloseModal now support inProgress for save button.

---

src/form/Toggle/Toggle.stories.tsx

Clicking the Toggle in the stories don't change anything except for
listing an action.
Added variables to store the value of the toggles to display the on and
off state.

fix: toggle in stories not working

---

src/table/EpicTable/EpicTable.scss
src/table/EpicTable/EpicTable.stories.tsx
src/table/EpicTable/EpicTable.tsx
src/table/EpicTable/cells/EpicCell/EpicCell.test.tsx
src/table/EpicTable/cells/EpicCell/EpicCell.tsx
src/table/EpicTable/cells/EpicCell/__snapshots__/EpicCell.test.tsx.snap
src/table/EpicTable/helpers/layout/layout.ts
src/table/EpicTable/rows/EpicRow/EpicRow.tsx

Whenever an `EpicCell` of an `EpicRow` which has the onClick property
is hovered all `EpicCell`'s of the `EpicRow` will display a hover effect
in the form of a changing background, and a cursor pointer.
Closes #450

feat: added support for EpicRow on click.

---

src/main.scss

Since we no longer use react-table these styles can be removed.
Closes #212

improvement: remove react-table related CSS

---

src/core/SearchInput/SearchInput.stories.tsx
src/core/SearchInput/SearchInput.test.tsx
src/core/SearchInput/SearchInput.tsx
src/form/IconPicker/IconPicker.tsx
src/form/IconPicker/__snapshots__/IconPicker.test.tsx.snap
src/form/ModalPicker/ModalPicker.tsx
src/form/ModalPicker/__snapshots__/ModalPicker.test.tsx.snap

SearchInput's value should be called defaultValue instead of value this
indicates better that it is an uncontrolled component.
Closes #220

improvement: renamed SearchInput property value to defaultValue

---

src/core/SearchInput/SearchInput.tsx
src/core/SearchInput/__snapshots__/SearchInput.test.tsx.snap

It is not clear what properties will work as well.
Removed rest from the input.
Closes #331

improvement: removed rest from SearchInput props

---

src/table/FormTable/FormTable.stories.tsx

To improve user experience, you could add a button "Copy for Excel"
which copies all content in an Excel friendly format.
It would be nice if you could also copy a table in Excel and paste it in
the EpicTable form, so there's no need for an "Import Excel" or "Import
CSV" button.
Added preview of how copy and paste functionality should be coded in
EpicForm stories.
Closes #361

improvement: added possibility to copy/paste to form in EpicTable

---

src/core/Toggle/Toggle.stories.tsx
src/core/Toggle/Toggle.test.tsx
src/core/Toggle/Toggle.tsx
src/core/Toggle/__snapshots__/Toggle.test.tsx.snap

The toggle is most useful when there's a label with it, but now
developers have to add the text next to it themselves.
Added optional label to the Toggle component.
Closes #506

improvement: label for Toggle

---

src/core/Card/Card.stories.tsx
src/core/Card/Card.test.tsx
src/core/Card/Card.tsx
src/core/Card/__snapshots__/Card.test.tsx.snap
src/index.test.ts
src/index.ts

We want a Card component which will have a suspense written into it.
Added Card component with suspense.
Closes #504

feature: card with suspense

---

src/core/BooleanIcon/BooleanIcon.test.tsx
src/core/BooleanIcon/BooleanIcon.tsx
src/core/Icon/Icon.tsx
src/core/SuccessIcon/SuccessIcon.test.tsx
src/core/SuccessIcon/SuccessIcon.tsx
src/form/FavoriteIcon/FavoriteIcon.test.tsx
src/form/FavoriteIcon/FavoriteIcon.tsx

All icon components should have an optional size, color, className and
onChange callback that is triggered on click.
Added size, color, className and onChange properties to all icon
components.
Closes #563

improvement: unify icon components

---

src/core/SearchInput/SearchInput.scss
src/core/SearchInput/SearchInput.stories.tsx
src/core/SearchInput/SearchInput.test.tsx
src/core/SearchInput/SearchInput.tsx
src/core/SearchInput/__snapshots__/SearchInput.test.tsx.snap
src/main.scss

It would be nice if the SearchInput showed a "X" button to clear the
content once it has a value.
Changed input type to search and added some styling to the browsers
search cancel button.
Closes #565

improvement: search input clear button

---

src/core/Debug/Debug.stories.tsx
src/core/Debug/Debug.test.tsx
src/core/Debug/Debug.tsx
src/core/Debug/__snapshots__/Debug.test.tsx.snap

When I am developing, I often want to know what a variable is at a
certain moment. To be able to know that, I could use console.log, but
then I have to search within all the console logging, or I could JSON
stringify the object. I would like to have a component to just pass the
variable I want to debug and it'll JSON stringify to make debugging
easier.
Added Debug component.
Closes #572

feature: debug

---

src/core/Tabs/Tab/Tab.test.tsx
src/core/Tabs/Tab/Tab.tsx
src/core/Tabs/Tab/__snapshots__/Tab.test.tsx.snap
src/core/Tabs/TabContent/TabContent.test.tsx
src/core/Tabs/TabContent/TabContent.tsx
src/core/Tabs/TabContent/__snapshots__/TabContent.test.tsx.snap
src/core/Tabs/Tabs.scss
src/core/Tabs/Tabs.stories.tsx
src/core/Tabs/Tabs.test.tsx
src/core/Tabs/Tabs.tsx
src/core/Tabs/__snapshots__/Tabs.test.tsx.snap
src/form/FormExample.stories.tsx
src/form/story-utils.tsx
src/index.test.ts
src/index.ts
src/main.scss
src/table/FormTable/FormTable.stories.tsx

It would be nice to have tabs where the content and navigation item are
together so you can disable a tab or specify if a user is allowed to see
a tab in one place without having to put the code all over the place.
The content should also be suspended to improve performance.
Added Tabs component.
Closes #569

feature: tabs

---

src/core/ConfirmModal/ConfirmModal.tsx
src/core/OpenClose/OpenClose.tsx
src/core/OrSeparator/OrSeparator.tsx
src/core/Tabs/Tab/Tab.tsx
src/core/lists/AttributeList/AttributeList.tsx
src/core/lists/AttributeView/AttributeView.tsx
src/form/PlainTextFormControl/PlainTextFormControl.tsx

Some of the components do not have a className prop yet.
Added className prop to components that do not have it yet.
Closes #578

improvement: add className prop

---

src/form/NewPasswordInput/NewPasswordInput.scss
src/form/NewPasswordInput/NewPasswordInput.tsx
src/form/NewPasswordInput/PasswordStrength/PasswordStrength.tsx
src/form/NewPasswordInput/PasswordStrength/__snapshots__/PasswordStrength.test.tsx.snap
src/form/NewPasswordInput/__snapshots__/NewPasswordInput.test.tsx.snap
src/main.scss

Fix was adding a height of 5px around the `Progress` component instead
via scss. Instead of setting the `style` property of the `Progress` to
5px because that only sets the inner progress bar.
Fixes #588

fix: NewPasswordInput strength indicator had strange border.

---

src/core/Card/Card.test.tsx
src/core/Card/Card.tsx
src/core/Card/__snapshots__/Card.test.tsx.snap

The Card component has modal...ClassName properties. They should be
renamed to card...ClassName.
Renamed classname properties to fit the component name better.
Closes #592

improvement: Card classname properties

---

src/core/CardOpenClose/CardOpenClose.tsx
src/core/CardOpenClose/__snapshots__/CardOpenClose.test.tsx.snap

The CardOpenClose should always suspense the body.
Added Suspense to the content of CardOpenClose.
Closes #591

improvement: CardOpenClose with Suspense

---

src/core/BooleanIcon/BooleanIcon.stories.tsx
src/core/BooleanIcon/BooleanIcon.test.tsx
src/core/BooleanIcon/BooleanIcon.tsx
src/core/FavoriteIcon/FavoriteIcon.stories.tsx
src/core/FavoriteIcon/FavoriteIcon.test.tsx
src/core/FavoriteIcon/FavoriteIcon.tsx
src/core/FavoriteIcon/__snapshots__/FavoriteIcon.test.tsx.snap
src/core/Icon/Icon.stories.tsx
src/core/Icon/Icon.test.tsx
src/core/Icon/Icon.tsx
src/core/Icon/__snapshots__/Icon.test.tsx.snap
src/core/SuccessIcon/SuccessIcon.stories.tsx
src/core/SuccessIcon/SuccessIcon.test.tsx
src/core/SuccessIcon/SuccessIcon.tsx
src/form/ValuePicker/__snapshots__/ValuePicker.test.tsx.snap

The BooleanIcon now accepts a color change on hover, but I would like to
see that functionality on Icon and all of its wrappers as well.
Added hoverColor to icon and all wrapping components.
Closes #582

improvement: icon hover color

---

package-lock.json
src/core/Icon/Icon.test.tsx
src/core/Icon/Icon.tsx
src/core/Icon/__snapshots__/Icon.test.tsx.snap

After the last release with the icon hover color, the non-hover color
turns out not to work correctly anymore.
Changed check to add correct color to the icon.
Added test and changed some tests to cover all possible layouts.
Closes #621

fix: icon color

---

src/core/Pagination/Pagination.scss
src/core/Pagination/Pagination.stories.tsx
src/core/Pagination/Pagination.test.tsx
src/core/Pagination/Pagination.tsx

It would be nice if the pagination component also has an option to 
change the page size so users can control how many items they see in a 
list.
Added page size dropdown to pagination component.

feature: pagination page size dropdown

---

src/form/ImageUpload/ImageUpload.test.tsx
src/form/ImageUpload/ImageUpload.tsx

Uploaded images should no longer be stretched out if they are smaller 
than the configured format. For these, the cropping step should be 
skipped.
When users selected an image, they often don't understand they have to 
click the done button as well to save the image. If they like what they 
see, they expect the image to be used as is automatically.
Added a check if the uploaded image is too small to skip the cropping 
step and use the image as is.
Uploaded images are now saved as soon as they are put in, rather than 
when a user is done with editing.
Closes #473
Closes #627

improvement: ImageUpload user experience

---

docs/translations.md
src/core/CopyToClipboard/CopyToClipboard.stories.tsx
src/core/CopyToClipboard/CopyToClipboard.test.tsx
src/core/CopyToClipboard/CopyToClipboard.tsx
src/core/CopyToClipboard/__snapshots__/CopyToClipboard.test.tsx.snap
src/index.test.ts
src/index.ts

Added a CopyToClipboard element, which copies the content of its child elements without HTML code.

Added a CopyToClipboard element

---

README.md
docs/directory-structure.md

We have to explain the breaking changes in the new version in the readme
Added migration guide to readme.

docs: migration guide

---

src/core/EpicPagination/EpicPagination.stories.tsx
src/core/EpicPagination/EpicPagination.test.tsx
src/core/EpicPagination/EpicPagination.tsx
src/core/EpicPagination/__snapshots__/EpicPagination.test.tsx.snap

The Pagination component has a page size dropdown, but the EpicPagination does not provide that feature yet.
Added optional page size dropdown to EpicPagination, similar to the one in Pagination.

improvement: add page size dropdown to EpicPagination
