- packages/core/Button/CHANGELOG.md
- packages/core/Button/package.json
- packages/core/Button/src/Button.tsx
- packages/core/Button/test/Button.test.tsx
- packages/core/ConfirmButton/package.json
- packages/core/SubmitButton/package.json
- packages/core/SubmitButton/src/SubmitButton.tsx
- packages/core/_bundle/package.json
The reason for this is sometimes you do not want an onClick. The
`SubmitButton` for example is of type 'submit'. This means that you
can submit via the `<form onSubmit>` instead.
Closes #8
> Feature: Button's onClick is now optional.

- packages/core/Breadcrumbs/example/Breadcrumbs.stories.tsx
- packages/core/Breadcrumbs/package.json
- packages/core/Breadcrumbs/src/Breadcrumbs.scss
- packages/core/Breadcrumbs/src/Breadcrumbs.tsx
- packages/core/Breadcrumbs/test/Breadcrumbs.test.tsx
- packages/core/Breadcrumbs/test/__snapshots__/Breadcrumbs.test.tsx.snap
Previous version of Breadcrumbs did not accept an active item. By adding
the `InactiveItem` and `ActiveItem` distinction it now accepts `active`
accordingly.
> feat: improve Breadcrumbs functionality

- .size-snapshot.json
- package-lock.json
- package.json
- src/core/FlashMessage/FlashMessage.scss
- src/core/FlashMessage/FlashMessage.stories.tsx
- src/core/FlashMessage/FlashMessage.test.tsx
- src/core/FlashMessage/FlashMessage.tsx
- src/core/FlashMessage/__snapshots__/FlashMessage.test.tsx.snap
- src/index.ts
Before the `FlashMessage` component used the `@42.nl/react-flash-messages`
library to render and close the flash messages. This is to much knowledge
of the way flash messages work. Now the flash message is simply a UI
component which does not know anything about `@42.nl/react-flash-messages`.
Users of `@42.nl/ui` should now implement their own flash message engine
or simply use: ``@42.nl/react-flash-messages`.
Also exposed `Color` in the default export.
Closes #78
> Improvement: dumped down the FlashMessage component.

- docs/_config.yml
- src/core/AsyncContent/AsyncContent.tsx
- src/form/FileInput/FileInput.test.tsx
- src/form/FileInput/FileInput.tsx
- src/form/FormError/utils.test.ts
- src/form/FormError/utils.ts
- src/form/ImageUpload/ImageUpload.test.tsx
- src/form/ImageUpload/ImageUpload.tsx
Sometimes a translated string is already passed through to the `translate` function provided by `@42.nl/ui`, which in turn tries to translate the translated string.
Additional changes:
* Fixed the link to the storybook in the documentation page.
* Renamed some translation keys to have correct spelling.
> Bugfix: enable bypassing of translation by providing a string

- .size-snapshot.json
- package-lock.json
- package.json
- src/core/NavigationItem/__snapshots__/NavigationItem.test.tsx.snap
Added more libraries which are common to 42 projects to the
`peerDependencies` list as well as included them to the `devDependencies`
list. This is due to issues with out-of-sync dependencies being used by
`@42.nl/ui` in conjunction to most of the internal 42 projects.
In addition this commit also resolves most of the `peerDependency`
warnings of the included dependencies.
---
The remaining `peerDependency` warnings are the following:
```
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.0.2 requires a peer of eslint-plugin-flowtype@3.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.0.2 requires a peer of …
```
> Improvement: expand peer dependencies

- package.json
- src/styling/_variables.scss
The previous declarations did not include `!default`, making it
impossible to override them.
Additional change:
- Removed provided dependency `@42.nl/jarb-final-form` from `peerDependencies`.
Fixes #74
---
* `!default`
https://sass-lang.com/documentation/variables#default-values
* theming Sass maps
https://getbootstrap.com/docs/4.0/getting-started/theming/
It might be nice to include theming in the documentation. Let me know and I will include this with this PR.
> Bugfix: enable theming by overriding default variables

- docs/translations.md
- src/core/Button/Button.scss
- src/core/Button/Button.stories.tsx
- src/core/Button/Button.test.tsx
- src/core/Button/Button.tsx
- src/core/Button/__snapshots__/Button.test.tsx.snap
- src/core/Pager/Pager.stories.tsx
- src/core/Pager/Pager.test.tsx
- src/core/Pager/Pager.tsx
- src/core/Pager/__snapshots__/Pager.test.tsx.snap
Feature: Added `Pager` component.
The Pager component shows a small variant of bootstraps pagination,
it only shows a previous and next button.
It supports working with a `Page` from `@42.nl/spring-connect`.
Improvement: Button now support placing the icon on the right.
Also fixed the spacing between the text and the icon in the button.
> Pager component, Button improvements, and translation docs.

- docs/translations.md
- src/core/AsyncContent/AsyncContent.stories.tsx
- src/core/AsyncContent/AsyncContent.test.tsx
- src/core/AsyncContent/AsyncContent.tsx
- src/core/AsyncContent/__snapshots__/AsyncContent.test.tsx.snap
When the `retry` button is `clicked` a call to `useAsync` return value
`reload` is called. By default this functionality is enabled but can
be disabled by setting `showRetryButton` to `false`.
Added better jsdoc documentation as well.
Also the title for the `loading` and `error` state can now be overridden
by the user.
Closes: #68
> Improvement: `AsyncContent` now shows retry button on failure.

- package-lock.json
- package.json
Probably an oversight from making all of the other packages peer dependencies but forgetting this one. Has been corrected.
> Improvement: add @42.nl/jarb-final-form to peer dependencies

- src/form/DateTimeInput/DateTimeInput.test.tsx
- src/form/DateTimeInput/DateTimeInput.tsx
- src/form/DateTimeInput/__snapshots__/DateTimeInput.test.tsx.snap
This allows it to be used outside of a form in cases were you do not
want a label. For example as a filter input inside another component.
> feat: DateTimeInput can now be used without a label.

- src/core/NavigationItem/Navigation.stories.tsx
- src/core/NavigationItem/NavigationItem.test.tsx
- src/core/NavigationItem/NavigationItem.tsx
Sometimes we use nested routes in applications, which do no work
nicely with the default `exact` property. For example when a user navigates
to `users/10` and we have a master-detail view, the `NavigationItem` will
not apply active to the entry, as it has an `exact` property by default.
This commit makes the `exact` configurable by the user to bypass this
behavior.
Fixes #120
> bug: The `NavigationItem` no longer forces `exact links

- .size-snapshot.json
- src/core/SearchInput/SearchInput.stories.tsx
- src/core/SearchInput/SearchInput.test.tsx
- src/core/SearchInput/SearchInput.tsx
- src/core/SearchInput/__snapshots__/SearchInput.test.tsx.snap
- src/form/ModalPicker/ModalPicker.test.tsx
- src/form/ModalPicker/ModalPicker.tsx
- src/form/ModalPicker/__snapshots__/ModalPicker.test.tsx.snap
- src/form/ModalPicker/multiple/ModalPickerMultiple.test.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.tsx
- src/form/ModalPicker/multiple/__snapshots__/ModalPickerMultiple.test.tsx.snap
- src/form/ModalPicker/single/ModalPickerSingle.test.tsx
- src/form/ModalPicker/single/ModalPickerSingle.tsx
- src/form/ModalPicker/single/__snapshots__/ModalPickerSingle.test.tsx.snap
- src/form/ValuePicker/__snapshots__/ValuePicker.test.tsx.snap
- src/index.ts
- src/main.scss
The `SearchInput` component is a small wrapper around the `reactstrap`
`Input` component which debounces the `onChange` by `500` milliseconds
by default. It uses `lodash`'s `debounce` under the hood.
Features:
1. When the user presses enter the `SearchInput` will skip the debounce
and set the value straight away.
2. The icon which is a magnifying class can be toggled on or of.
3. The debounce timeout can also be set to a custom value.
4. The debounce settings which lodash accepts can also be set for
maximum configurability.
The modal pickers now use the `SearchInput` instead of debouncing the
inputs themselves.
Also had to set the border color in `.form-control:focus` to a gray
to prevent it from becoming blue for the `SearchInput`.
Closes #191
> feat: Added SearchInput component.

- src/form/Select/Select.stories.tsx
- src/form/Select/Select.test.tsx
- src/form/Select/Select.tsx
- src/form/Select/__snapshots__/Select.test.tsx.snap
- src/form/ValuePicker/__snapshots__/ValuePicker.test.tsx.snap
In the previous version of `Select` the placeholder was a non-selectable
option which in turn shows the first item in the options as selected,
even though it is not selected. This is resolved by making the
placeholder a selectable option.
~Additionally this change contains a fix for object equality when passing
a value to `Select`. This is done by using `Lodash.isEqual` instead of
trying to do equal comparison.~
Fixes #137.
> fix: select placeholder is now a selectable option

- src/table/EpicTable/EpicTable.stories.tsx
- src/table/EpicTable/EpicTable.tsx
- src/table/EpicTable/helpers/GooeyCenter/GooeyCenter.tsx
- src/table/EpicTable/helpers/layout/layout.ts
Multiple people are taken aback by the shadows produced on a very small
table. This is because they do not see that the center can be scrolled
in this case. So when a table is small enough not to need a horizontal
scrollbar it should not render the shadows and instead be more flat.
The technical solution is to calculate the total desired width of the
center as given by the user. When the desired width can be met, there is
no need for a horizontal scrollbar. In that case we do not render shadows
around the left and right column, but only around the container.
Also the `GooeyCenter` now renders at 100% width to prevent width
flickering.
Closes #230
> improvement: EpicTable is now flat when no horizontal scrollbar is shown

- src/table/EpicTable/EpicTable.scss
- src/table/EpicTable/EpicTable.stories.tsx
- src/table/EpicTable/EpicTable.tsx
- src/table/EpicTable/cells/EpicCell/EpicCell.tsx
- src/table/EpicTable/helpers/GooeyCenter/GooeyCenter.tsx
- src/table/EpicTable/helpers/layout/layout.ts
The `EpicCell` now has an injected property called `odd`. When `odd` is
`true` the cell sets a CSS class called `epic-table-cell--odd` which set
a transparent blue background color.
The `odd` property is injected by the `EpicTableLayout` based on the
number of encountered `EpicRow`'s. Each section resets the count so each
sections starts fresh.
`GooeyCenter` now has to recalculate whenever the left, right and center
change, otherwise the zebra stripes will bleed through the right column
of the EpicTable.
Closes: #238
> improvement: `EpicTable` is now striped like a zebra by default.

- src/form/IconPicker/IconPicker.tsx
- src/form/IconPicker/__snapshots__/IconPicker.test.tsx.snap
Previously it had the default HTML property of a button as it was not
given, which is `submit`. Resulting in clicking on the `IconPicker`
button in a form to submit the entire form.
> fix: IconPicker button type to 'button'

- src/core/SearchInput/SearchInput.tsx
Because the `onChange` callback is wrapped inside of a `useRef` which
in turn calls `lodash.debounce`. The `useRef` will not update anything
when the `useRef` functions params change.
We must do this manually, added an `useEffect` which updates the
`useRef.current` whenever the params to the `debounce` change.
This way a new `onChange` callback is actually used.
Closes: #265
> fix: SearchInput did not update the `onChange` callback.

- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.stories.tsx
- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.test.tsx
- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.stories.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.tsx
- src/form/ModalPicker/single/ModalPickerSingle.stories.tsx
- src/form/ModalPicker/single/ModalPickerSingle.tsx
- src/form/Select/Select.stories.tsx
- src/form/Select/Select.test.tsx
- src/form/Select/Select.tsx
- src/form/Typeahead/multiple/TypeaheadMultiple.tsx
- src/form/Typeahead/single/TypeaheadSingle.tsx
- src/form/ValuePicker/ValuePicker.stories.tsx
- src/form/ValuePicker/ValuePicker.test.tsx
- src/form/ValuePicker/ValuePicker.tsx
- src/form/ValuePicker/__snapshots__/ValuePicker.test.tsx.snap
- src/form/option.test.tsx
- src/form/option.ts
- src/form/types.ts
- src/test/fixtures.ts
Before the equality of selections were determined based on if the two
values had the same label. This is a good heuristic for the default
implementation, which it still is.
Now however the user can supply a custom checker via the `isOptionEqual`
prop. Here the user implements a feature that gives two values and must
return a boolean. This allows the user to have full control of the
check whether a value is selected or not.
For example you could implement `isOptionEqual` like this to check the
`id` of the items.
```tsx
<ValuePicker
{/* Rest of the props omitted for brevity */}
isOptionEqual={(a: User, b: User) => a.id === b.id}
/>
```
You could even use `lodash.isEqual` when you really want a deep check
for equality:
```tsx
<ValuePicker
{/* Rest of the props omitted for brevity */} …
```
> improvement: all ValuePickers support custom `isOptionEqual` checks now.

- src/table/EpicTable/EpicTable.stories.tsx
- src/table/EpicTable/EpicTable.tsx
- src/table/EpicTable/helpers/layout/layout.ts
- src/table/EpicTable/rows/EpicDetailRow/EpicDetailRow.tsx
This had the effect that when the `EpicDetailRow` is bigger than the
`EpicTable` it would become bigger than the `EpicTable` itself. Possible
overflowing other elements on the page. Which looks strange.
To fix this the `EpicTable`'s height is now based on three things:
1. The minHeight props of the EpicTable.
2. The height of the EpicDetailRow.
3. The desired height of the EpicTable, which is the height of one row.
Which ever height is the largest height becomes the actual height of
the `EpicTable`.
Whenever an EpicDetailRow is active it will adjust its height to the
actual height of the `EpicTable`
Fixes: #269
> fix: `EpicTable` did not grow with the `EpicDetailRow`.

- src/form/story-utils.tsx
Because the `Col` of the `FinalForm` component did not have a size
constraints it will by default try do divide the width evenly.
Because the `<pre>` element gets really large when the user enters a
large value into the `Textarea` the division of width is unfairly given
to the right `Col`.
Fixed by adding a `lg={6}` to the `Col`'s making the widths explicit.
This prevents `bootstrap` from dividing the width itself.
Fixes: #80
> fix: form example strange text-area resizing bug.

- src/table/EpicTable/EpicTable.scss
The `EpicTable` used the `$primary` for the `background-color` for
the header. But this is not correct and should be:
`background-color: map-get($theme-colors, primary);`.
This way the user can override the color from their own scss.
Closes: #319
> fix: the `EpicTable` color could not be overridden.

- package-lock.json
- package.json
- src/core/Tooltip/Tooltip.stories.tsx
- src/core/Tooltip/Tooltip.test.tsx
- src/core/Tooltip/Tooltip.tsx
- src/core/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- src/main.scss
Added a Bootstrap style Tooltip component based on Tippy.js
The Tooltip can be wrapped around the target component. On hover the Tooltip will be shown on this component.
Internally the Tooltip wraps the target inside of a CustomTag (this can be a div or a span).
This CustomTag gets a tabIndex={0} for the sake of handeling the forwardRef.
You can add content to the Tooltip which is displayed on hover over the Target component.
This content can be other React components as well.
Styling can be done through several properties such as placement, distance from target, interactivity, maxWidth, bootstrap classNames and css style.
> feat: added Tooltip

- src/core/SearchInput/SearchInput.stories.tsx
- src/core/SearchInput/SearchInput.test.tsx
- src/core/SearchInput/SearchInput.tsx
- src/core/SearchInput/__snapshots__/SearchInput.test.tsx.snap
- src/form/ModalPicker/ModalPicker.tsx
- src/form/ModalPicker/__snapshots__/ModalPicker.test.tsx.snap
You might want to display a label above the SearchInput to clarify which
SearchInput is used for what purpose in cases where multiple SearchInput
are used inside the same frame/component.
Added possibility to specify a label to display above the input field.
Wraps the field in a FromGroup when label is specified.
Closes #336
> Added optional label to SearchInput

- src/core/SearchInput/SearchInput.test.tsx
- src/core/SearchInput/SearchInput.tsx
- src/core/SearchInput/__snapshots__/SearchInput.test.tsx.snap
Size is used when showIcon is true, but size is not defined in props.
Therefor size is not type-safe. People might not know they could change
the size of the icon or what the available sizes are.
Separated Props into 2 different interfaces, one with showIcon true
which has an optional size, the other with optional showIcon false
where size is not allowed.
Closes #334
> Fix: Defined size as property of SearchInput

- src/form/ModalPicker/multiple/ModalPickerMultiple.stories.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.test.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.tsx
- src/form/ModalPicker/single/ModalPickerSingle.stories.tsx
- src/form/ModalPicker/single/ModalPickerSingle.test.tsx
- src/form/ModalPicker/single/ModalPickerSingle.tsx
- src/form/option.ts
You might, for example, want to display the options in the
ModalPicker with a profile image when selecting users.
Added renderOptions callback which you can use to customize
how the options are displayed in a ModalPicker.
Closes #333
> Added possibility to customize ModalPicker options

- src/core/Avatar/Avatar.test.tsx
- src/core/Avatar/Avatar.tsx
- src/core/Button/Button.tsx
- src/core/SearchInput/SearchInput.tsx
- src/core/SubmitButton/SubmitButton.tsx
- src/core/SubmitButton/__snapshots__/SubmitButton.test.tsx.snap
- src/core/types.ts
Bootstrap sizes like 'xs' | 'sm' | 'md' | 'lg' are used and defined in
multiple files. This should be separated into a BootstrapSize type
defined in one place.
Closes #339
> Fix: Bootstrap sizes should be a registered type

- src/core/SearchInput/SearchInput.tsx
- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.stories.tsx
- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.test.tsx
- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.tsx
- src/form/CheckboxMultipleSelect/__snapshots__/CheckboxMultipleSelect.test.tsx.snap
- src/form/RadioGroup/RadioGroup.stories.tsx
- src/form/RadioGroup/RadioGroup.test.tsx
- src/form/RadioGroup/RadioGroup.tsx
- src/form/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
- src/form/ValuePicker/__snapshots__/ValuePicker.test.tsx.snap
If you want to display inputs i.e. in a table, it might be better to
display options horizontally instead of vertically.
Added horizontal mode to RadioGroup and CheckboxMultipleSelect to allow
for options to be displayed horizontally instead of vertically.
Closes #355
> improvement: added horizontal mode to multiple checkbox/radio

- src/core/Button/Button.tsx
- src/core/ConfirmButton/ConfirmButton.test.tsx
- src/core/ConfirmButton/ConfirmButton.tsx
- src/form/Input/Addon/Addon.tsx
In Addon, you can specify icon and text without warning.
Added `text?: never` to IconProps and `icon?: never` to TextProps so
you'll get a warning that icon and text cannot be used together.
Did the same with ConfirmButton where icon and children should never be
`undefined`, they either have a valid value or they're not specified at
all.
Closes #335
> Fix: Type integrity

- src/core/types.ts
Because the Color type in types.ts starts with a pipeline, it is seen as
a statement (which is not tested).
Added a comment to make tests ignore the types file.
> fix: types.ts prevents coverage of 100%

- src/form/FormError/FormError.tsx
- src/form/FormError/__snapshots__/FormError.test.tsx.snap
- src/form/withJarb/__snapshots__/withJarb.test.tsx.snap
- src/form/withJarb/useHasErrors/useHasErrors.test.ts
- src/form/withJarb/useHasErrors/useHasErrors.ts
- src/form/withJarb/withJarb.scss
- src/form/withJarb/withJarb.test.tsx
- src/form/withJarb/withJarb.tsx
- src/main.scss
If you want to display a form in an EpicTable, showing errors below the
inputs will clutter the frame. Instead, you could display the errors in
a tooltip that'll show on hover.
Added the possibility to specify if the errors should be displayed in a
tooltip or not. Defaults to displaying the errors underneath the input.
Closes #358
> improvement: withJarb errors in tooltip

- src/core/AsyncPage/AsyncPage.stories.tsx
The console gives a warning about a duplicate ID being used for stories
in AsyncPage. Also, the duplicate ID caused one of the stories not to be
displayed in the menu.
Changed the ID for one of the stories so there is no warning anymore and
both of the stories are displayed in the menu.
> fix: duplicate ID in asyncPage stories

- src/form/FormError/FormError.tsx
- src/form/FormError/__snapshots__/FormError.test.tsx.snap
- src/form/FormError/utils.test.tsx
- src/form/FormError/utils.tsx
- src/form/FormExample.stories.tsx
- src/form/types.ts
- src/form/withJarb/__snapshots__/withJarb.test.tsx.snap
This way, the user can render errors in a custom element, for example as
a list item.
Replaced string with ReactNode as type of MetaError to accept custom
nodes as well.
Uses the index as key when mapping ReactNode errors.
Closes #369
> improvement: withJarb support accepting errors as React.ReactNode

- src/form/ModalPicker/ModalPickerOpener/ModalPickerOpener.test.tsx
- src/form/ModalPicker/ModalPickerOpener/ModalPickerOpener.tsx
- src/form/ModalPicker/ModalPickerOpener/__snapshots__/ModalPickerOpener.test.tsx.snap
- src/form/ModalPicker/ModalPickerOpener/useComponentOverflow/useComponentOverflow.test.ts
- src/form/ModalPicker/ModalPickerOpener/useComponentOverflow/useComponentOverflow.ts
- src/form/ModalPicker/ModalPickerOpener/useResizeObserver/useResizeObserver.test.ts
- src/form/ModalPicker/ModalPickerOpener/useResizeObserver/useResizeObserver.ts
- src/form/ModalPicker/ModalPickerOpener/useResizeObserver/utils.ts
- src/form/ModalPicker/multiple/ModalPickerMultiple.test.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.tsx
- src/form/ModalPicker/multiple/__snapshots__/ModalPickerMultiple.test.tsx.snap
- src/form/ModalPicker/single/ModalPickerSingle.test.tsx
- src/form/ModalPicker/single/ModalPickerSingle.tsx
- src/form/ModalPicker/single/__snapshots__/ModalPickerSingle.test.tsx.snap
- src/form/ValuePicker/__snapshots__/ValuePicker.test.tsx.snap
When ModalPickerSingle is used within a fixed-width container like a
table cell, a long label should not cause the button to be (partly)
hidden.
Closes #365
> fix: ModalPickerSingle should not overflow a fixed-width container

- src/form/TextEditor/TextEditor.stories.tsx
- src/form/TextEditor/TextEditor.test.tsx
- src/form/TextEditor/TextEditor.tsx
- src/form/TextEditor/__snapshots__/TextEditor.test.tsx.snap
It would be nice to have an option to add a custom dropdown to the
TextEditor toolbar to i.e. provide placeholders when writing an e-mail
template.
Added modules prop to TextEditor to specify custom options
like a custom toolbar.
> improvement: Added possibility to customize TextEditor toolbar

- src/form/RadioGroup/RadioGroup.scss
- src/form/RadioGroup/RadioGroup.tsx
- src/form/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
- src/form/ValuePicker/__snapshots__/ValuePicker.test.tsx.snap
- src/main.scss
The label of a radio group is too large. Other inputs have a smaller
label, so when put together, it doesn't look too well.
Added a bit of styling to match the size of the RadioGroup legend to the
labels of other form components.
Closes #387
> fix: RadioGroup label size

- docs/translations.md
- src/core/ConfirmButton/ConfirmButton.test.tsx
- src/core/ConfirmButton/ConfirmButton.tsx
- src/core/ConfirmButton/__snapshots__/ConfirmButton.test.tsx.snap
- src/core/OpenCloseModal/OpenCloseModal.stories.tsx
- src/core/OpenCloseModal/OpenCloseModal.test.tsx
- src/core/OpenCloseModal/OpenCloseModal.tsx
- src/core/OpenCloseModal/__snapshots__/OpenCloseModal.test.tsx.snap
- src/index.ts
It would be nice to have a component that predefines the basics of a
modal so you only need 3 lines for the basics instead of 15.
Added OpenCloseModal component that predefines the basic layout of a
modal with cancel and save button.
Closes #384
> improvement: generic modal layout

- docs/translations.md
- src/form/DateRangePicker/DateRangePicker.stories.tsx
- src/form/DateRangePicker/DateRangePicker.test.tsx
- src/form/DateRangePicker/DateRangePicker.tsx
- src/form/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
- src/form/DateTimeInput/DateTimeInput.scss
- src/form/DateTimeInput/DateTimeInput.stories.tsx
- src/form/DateTimeInput/DateTimeInput.test.tsx
- src/form/DateTimeInput/DateTimeInput.tsx
- src/form/DateTimeInput/DateTimeModal/DateTimeModal.test.tsx
- src/form/DateTimeInput/DateTimeModal/DateTimeModal.tsx
- src/form/DateTimeInput/DateTimeModal/__snapshots__/DateTimeModal.test.tsx.snap
- src/form/DateTimeInput/DateTimeModal/useValue.ts
- src/form/DateTimeInput/__snapshots__/DateTimeInput.test.tsx.snap
- src/form/DateTimeInput/useHasFormatError/useHasFormatError.ts
- src/form/DateTimeInput/useIsModalOpen/useIsModalOpen.ts
When used in EpicTable, the DateTimeInput causes extra blank space
underneath the content of the table, so the content will become
scrollable vertically. It should be possible to display the date picker
in a modal. That way, the date picker doesn't conflict visually when
used in a table.
Added an option to display a button next to the inpit that will open the
datepicker in a modal when clicked.
Closes #382
> improvement: DateTimeInput datepicker in modal

- package.json
- src/form/DateTimeInput/DateTimeInput.test.tsx
- src/form/DateTimeInput/DateTimeModal/DateTimeModal.test.tsx
You don't want to have to restore all mocks manually after each test.
Changed restoreMocks in jest configuration.
Removed all mockRestore() calls.
> fix: restore all mocks after each test

- src/form/ValuePicker/ValuePicker.tsx
- src/form/ValuePicker/__snapshots__/ValuePicker.test.tsx.snap
When you have a ModalPickerMultiple component with a lot of options and you try to narrow the number of options down by using the search option, the modal closes sometimes.
This seems to happen when you narrow it down too much.
The cause of this problem lies in the containing ValuePicker component.
This component wraps several other components and displays the right one
based on the total options. When the ModalPicker narrows the number of
options, the value of the total options in the ValuePicker was also
changed. The ValuePicker wraps the given optionFetcherCallback in its
own callback function. In this function it updates the total number of
options. And this callback function is passed to its child components.
Moved setting the total elements to the boot function to prevent total …
> fix: modal closed when valuepicker total elements narrowed by search

- docs/translations.md
- src/form/FormExample.stories.tsx
- src/form/NewPasswordInput/NewPasswordInput.stories.tsx
- src/form/NewPasswordInput/NewPasswordInput.test.tsx
- src/form/NewPasswordInput/NewPasswordInput.tsx
- src/form/NewPasswordInput/PasswordStrength/PasswordStrength.test.tsx
- src/form/NewPasswordInput/PasswordStrength/PasswordStrength.tsx
- src/form/NewPasswordInput/PasswordStrength/__snapshots__/PasswordStrength.test.tsx.snap
- src/form/NewPasswordInput/PasswordStrength/rules.test.ts
- src/form/NewPasswordInput/PasswordStrength/rules.ts
- src/form/NewPasswordInput/PasswordStrength/useMeterWidth/useMeterWidth.test.ts
- src/form/NewPasswordInput/PasswordStrength/useMeterWidth/useMeterWidth.ts
- src/form/NewPasswordInput/PasswordStrength/useRules/useRules.test.tsx
- src/form/NewPasswordInput/PasswordStrength/useRules/useRules.ts
- src/form/NewPasswordInput/__snapshots__/NewPasswordInput.test.tsx.snap
- src/index.ts
There should be an input element that displays the strength of a 
password using some kind of progress bar and a list of requirements for 
the password.
Added NewPasswordInput component.
Closes #418
> feat: input with password strength

- src/core/Popover/Popover.stories.tsx
- src/core/Popover/Popover.test.tsx
- src/core/Popover/Popover.tsx
- src/core/Popover/__snapshots__/Popover.test.tsx.snap
When the isOpen property is used in the Popover, even though hideOnClick
is true, clicking outside the popover doesn't close the popover, because
the isOpen boolean is static and not manageable by the Popover itself.
Replaced hideOnClick with onClickOutside to take control of what happens
when you click outside the popover.
Closes #424
> fix: popover not closed when clicked outside

- src/core/AsyncList/__snapshots__/AsyncList.test.tsx.snap
- src/core/AsyncPage/__snapshots__/AsyncPage.test.tsx.snap
- src/form/ModalPicker/ModalPickerOpener/ModalPickerOpener.test.tsx
- src/form/ModalPicker/ModalPickerOpener/ModalPickerOpener.tsx
- src/form/ModalPicker/ModalPickerOpener/__snapshots__/ModalPickerOpener.test.tsx.snap
- src/form/ModalPicker/multiple/ModalPickerMultiple.stories.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.test.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.tsx
- src/form/ModalPicker/multiple/__snapshots__/ModalPickerMultiple.test.tsx.snap
- src/form/ModalPicker/single/ModalPickerSingle.stories.tsx
- src/form/ModalPicker/single/ModalPickerSingle.test.tsx
- src/form/ModalPicker/single/ModalPickerSingle.tsx
- src/form/ModalPicker/single/__snapshots__/ModalPickerSingle.test.tsx.snap
- src/form/RadioGroup/RadioGroup.test.tsx
- src/form/Select/Select.test.tsx
- src/form/Typeahead/multiple/__snapshots__/TypeaheadMultiple.test.tsx.snap
- src/form/Typeahead/single/__snapshots__/TypeaheadSingle.test.tsx.snap
- src/form/ValuePicker/__snapshots__/ValuePicker.test.tsx.snap
- src/test/fixtures.ts
- src/test/types.ts
In some cases you only want to display the button to open the modal of a
ModalPicker, or you want to display another value than you see in the
options (optionForValue).
Added an optional callback property to customize the selected values
display.
> improvement: optional callback to display selected item(s) in ModalPicker

- src/core/LoadingPage/LoadingPage.stories.tsx
- src/core/LoadingPage/LoadingPage.test.tsx
- src/core/LoadingPage/LoadingPage.tsx
- src/core/LoadingPage/__snapshots__/LoadingPage.test.tsx.snap
- src/core/useShowAfter/useShowAfter.test.tsx
- src/core/useShowAfter/useShowAfter.tsx
- src/index.ts
When the new height property is optional. When it is provided the height
of the popover is no longer the fullscreen.
Refactored the hook `LoadingPage` used to its own file, and called if
`useShowAfter`. Also exposing the `useShowAfter` hook now so users of
our library can use it as well.
Closes #431
> improvement: LoadingPage now accepts custom height and style.

- docs/translations.md
- src/core/TextButton/TextButton.stories.tsx
- src/core/TextButton/TextButton.test.tsx
- src/core/TextButton/TextButton.tsx
- src/core/TextButton/__snapshots__/TextButton.test.tsx.snap
- src/form/ColorPicker/ColorPicker.test.tsx
- src/form/ColorPicker/ColorPicker.tsx
- src/form/ColorPicker/__snapshots__/ColorPicker.test.tsx.snap
- src/form/IconPicker/IconPicker.test.tsx
- src/form/IconPicker/IconPicker.tsx
- src/form/IconPicker/__snapshots__/IconPicker.test.tsx.snap
- src/form/ModalPicker/ModalPickerOpener/ModalPickerOpener.test.tsx
- src/form/ModalPicker/ModalPickerOpener/ModalPickerOpener.tsx
- src/form/ModalPicker/ModalPickerOpener/__snapshots__/ModalPickerOpener.test.tsx.snap
- src/form/ModalPicker/multiple/ModalPickerMultiple.test.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.tsx
- src/form/ModalPicker/multiple/__snapshots__/ModalPickerMultiple.test.tsx.snap
- src/form/ModalPicker/single/ModalPickerSingle.test.tsx
- src/form/ModalPicker/single/ModalPickerSingle.tsx
- src/form/ModalPicker/single/__snapshots__/ModalPickerSingle.test.tsx.snap
- src/form/RadioGroup/RadioGroup.stories.tsx
- src/form/RadioGroup/RadioGroup.test.tsx
- src/form/RadioGroup/RadioGroup.tsx
- src/form/ValuePicker/ValuePicker.tsx
- src/form/ValuePicker/__snapshots__/ValuePicker.test.tsx.snap
- src/index.ts
The clear behavior in the `ModalPickerMultiple` and `ModalPickerSingle`
acts and looks and acts the same as the `IconPicker` and `ColorPicker`.
The `RadioGroup` renders the clear button above the radio inputs. But
only when the new `canClear` props is set to `true`.
The `ValuePicker`'s `RadioGroup` will set the `canClear` props to
`true`. This way all `ValuePicker` variants van clear the selection.
Extracted the shared "clear" button into a `TextButton` component which
is also exposed.
Closes #428
> improvement: RadioGroup, and the modalpickers can now clear the value.

- src/form/TextEditor/TextEditor.scss
You can only start typing when you click the first line of the
TextEditor. Clicking anywhere else in the editor block doesn't work.
Changed the min-height rule from container to editor.
Closes #430
> fix: TextEditor only first line clickable

- src/core/OpenCloseModal/OpenCloseModal.tsx
- src/core/useBodyFixOnModalClose/useBodyFixOnModalClose.ts
- src/form/ModalPicker/ModalPicker.tsx
The modal-open class remains on the body tag even after the modal is
closed. This is an issue of the reactstrap library
(https://github.com/reactstrap/reactstrap/issues/1323) which is already
fixed buy not released yet.
Added a temporary work-around to remove the modal-open class when modal
is closed.
Closes #426
> fix: modal-open class remains on body after modal closed

- package-lock.json
- package.json
- src/form/RadioGroup/RadioGroup.stories.tsx
- src/form/RadioGroup/RadioGroup.tsx
- src/form/Select/Select.stories.tsx
- src/form/Select/Select.tsx
- src/form/useOptions.test.ts
- src/form/useOptions.ts
In Select and RadioGroup, when the options property is an array, the 
options displayed are not updated when the options array changes.
When the options property is an OptionsFetcher that uses an external 
value, there is no possibility to reload the options.
Changed behaviour of options when it's an array.
Added watch property to RadioGroup and Select to watch for external 
changes that influence the result of the OptionsFetcher and trigger the 
fetcher when the value changes.
> fix: update RadioGroup options when options change

- src/form/ImageUpload/ImageUpload.stories.tsx
- src/form/ImageUpload/ImageUpload.test.tsx
- src/form/ImageUpload/ImageUpload.tsx
When ImageUpload is rendered conditionally, the initial value could be
an instance of File. Currently, when that happens, a preview of the
image is not displayed.
Modified componentDidMount to handle File as initial value.
> fix: ImageUpload handle File as initial value

- src/core/Button/Button.stories.tsx
- src/core/Button/Button.test.tsx
- src/core/Button/Button.tsx
- src/core/Button/__snapshots__/Button.test.tsx.snap
- src/core/ConfirmButton/ConfirmButton.stories.tsx
- src/core/ConfirmButton/ConfirmButton.tsx
- src/core/SubmitButton/SubmitButton.tsx
Also improved the type of the `Button` size. It does not support all
bootstrap sizes, it only supports `'sm' | 'md' | 'lg'` the type now
reflects this.
Also added a story for the sizes of the button.
Closes #443
> improvement: Button / ConfirmButton now support fullWidth

- src/core/OpenCloseModal/OpenCloseModal.scss
- src/core/OpenCloseModal/OpenCloseModal.stories.tsx
- src/core/OpenCloseModal/OpenCloseModal.test.tsx
- src/core/OpenCloseModal/OpenCloseModal.tsx
- src/core/OpenCloseModal/__snapshots__/OpenCloseModal.test.tsx.snap
- src/form/FormExample.stories.tsx
- src/main.scss
The sticky footer is enabled by default but can be disabled. When
enabled it will make the footer stay with the user, this way the user
can always press the save and cancel buttons.
The save and cancel buttons also have an icon by default now. The
icons can optionally be changed by the user. The default icons are
`save` and `cancel`.
Also added a story on how to properly use a final-form `Form` inside
of the `OpenCloseModal`. It uses the same form as the `FormExample`
which exports it now. Added it on two locations: with the `FormExample`
and the `OpenCloseModal`, so it can be found more easily.
Closes #452
> improvement: OpenCloseModal now has icons and supports a sticky footer

- src/core/AsyncList/AsyncList.stories.tsx
- src/core/AsyncList/AsyncList.test.tsx
- src/core/AsyncPage/AsyncPage.stories.tsx
- src/core/AsyncPage/AsyncPage.test.tsx
- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.stories.tsx
- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.test.tsx
- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.tsx
- src/form/FormExample.stories.tsx
- src/form/ModalPicker/ModalPickerOpener/ModalPickerOpener.test.tsx
- src/form/ModalPicker/ModalPickerValueTruncator/ModalPickerValueTruncator.test.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.stories.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.test.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.tsx
- src/form/ModalPicker/single/ModalPickerSingle.stories.tsx
- src/form/ModalPicker/single/ModalPickerSingle.test.tsx
- src/form/RadioGroup/RadioGroup.stories.tsx
- src/form/RadioGroup/RadioGroup.test.tsx
- src/form/Select/Select.stories.tsx
- src/form/Select/Select.test.tsx
- src/form/Typeahead/multiple/TypeaheadMultiple.stories.tsx
- src/form/Typeahead/multiple/TypeaheadMultiple.test.tsx
- src/form/Typeahead/single/TypeaheadSingle.stories.tsx
- src/form/Typeahead/single/TypeaheadSingle.test.tsx
- src/form/ValuePicker/ValuePicker.stories.tsx
- src/form/ValuePicker/ValuePicker.test.tsx
- src/form/useOptions.test.ts
- src/test/fixtures.ts
The deselect broke when using a custom `isOptionEqual` callback. The
idea of the `isOptionEqual` is that you can say that two objects are
equal based on something other than the default reference equality.
The canonical usecase being checking two `id`'s.
In both the `CheckboxMultipleSelect`, and `ModalPickerMultiple` when
clicking an option a routine is executed when an option is selected,
which should remove it when it is already selected.
In both cases de deselection uses a filter:
```ts
selected = selected.filter(v: T) => v !== item);
```
Of course this filter uses simple reference equality. Which in cases
when using `isOptionEqual` breaks, because the user will provide us with
different `objects` each time, which of course breaks selection.
The fix is using the `isOptionEqual` …
> fix: CheckboxMultipleSelect, and ModalPickerMultiple deselect was broken

- src/form/DateRangePicker/DateRangePicker.stories.tsx
- src/form/DateRangePicker/DateRangePicker.test.tsx
- src/form/DateRangePicker/DateRangePicker.tsx
- src/form/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
- src/form/DateTimeInput/DateTimeInput.test.tsx
- src/form/DateTimeInput/DateTimeInput.tsx
- src/form/DateTimeInput/DateTimeModal/DateTimeModal.tsx
- src/form/DateTimeInput/DateTimeModal/__snapshots__/DateTimeModal.test.tsx.snap
When `horizontal` is `false` it will render vertically. By default it
will render horizontally.
Also gave the `mode` a shared type definition.
Closes: #444
> improvement: added vertical mode to DateRangePicker.

- storybook/preview.js
- storybook/show-code-fix.scss
The "show code" would add CSS on the `.tag` and `.token` which clashed
with the CSS from our own `Tag` component. Fixed by resetting the style
for `.token` and `.tag` under `pre.hljs > code` elements.
Thanks @arjanvlek.
Closes: #94
> fix: storybook "show code" was broken.

- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.tsx
- src/form/CheckboxMultipleSelect/__snapshots__/CheckboxMultipleSelect.test.tsx.snap
- src/form/ModalPicker/multiple/ModalPickerMultiple.tsx
- src/form/ModalPicker/single/ModalPickerSingle.tsx
- src/form/RadioGroup/RadioGroup.tsx
- src/form/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
- src/form/Select/Select.tsx
- src/form/Select/__snapshots__/Select.test.tsx.snap
- src/form/ValuePicker/ValuePicker.tsx
- src/form/ValuePicker/__snapshots__/ValuePicker.test.tsx.snap
- src/form/option.test.tsx
- src/form/option.ts
- src/form/useOptions.ts
Every form element with multiple options use the label as key for
mapping, but the label is not always unique. This sometimes causes more
options to be displayed than actually should be displayed.
Added optional uniqueKeyForValue property to get unique property for an
item.
> fix: options mapping

- docs/translations.md
- package-lock.json
- package.json
- src/config/config.test.ts
- src/config/config.ts
- src/form/withJarb/__snapshots__/withJarb.test.tsx.snap
- src/form/withJarb/components/MarkedAsRequiredLabel/MarkedAsRequiredLabel.test.tsx
- src/form/withJarb/components/MarkedAsRequiredLabel/MarkedAsRequiredLabel.tsx
- src/form/withJarb/components/MarkedAsRequiredLabel/__snapshots__/MarkedAsRequiredLabel.test.tsx.snap
- src/form/withJarb/withJarb.tsx
- src/index.ts
When using a Jarb field, the field should know if it's required, so it
should be possible to add a required mark to the label when the field is
required.
Added check that adds required mark to label in Jarb fields when the
field is required.
Added configure function to optionally disable required mark entirely.
Closes #465
> improvement: required mark in label

- src/form/ImageUpload/ImageUpload.scss
When an image is selected in the ImageUpload component, the editor
exceeds the container borders and therefor sometimes even the window
borders.
Added CSS rules to maximize the canvas size without messing up the
image ratio.
Closes #467
> fix: ImageUpload exceeds container size in edit mode

- src/form/ImageUpload/ImageUpload.test.tsx
- src/form/ImageUpload/ImageUpload.tsx
- src/form/ImageUpload/utils.test.ts
- src/form/ImageUpload/utils.ts
ImageUpload accepts any image, but the output is always a PNG file. The
output file doesn't have the .png extension though. This is not a
problem for browsers, as they don't use the extension, but the
extension should match the contents.
Added a function that replaces the file extension with .png.
Added an optional property to keep the original file name.
Closes #480
> fix: ImageUpload replace file extension to match output

- src/core/ConfirmButton/ConfirmButton.test.tsx
- src/core/ConfirmButton/ConfirmButton.tsx
- src/core/ConfirmButton/__snapshots__/ConfirmButton.test.tsx.snap
- src/core/ConfirmModal/ConfirmModal.stories.tsx
- src/core/ConfirmModal/ConfirmModal.test.tsx
- src/core/ConfirmModal/ConfirmModal.tsx
- src/core/ConfirmModal/__snapshots__/ConfirmModal.test.tsx.snap
Added `ConfirmModal`, which is based on `OpenCloseModal` and offers
the user a confirmation before performing an action.
A confirmation dialog was previously only accessible through
`ConfirmButton`. While `ConfirmButton` remains the primary choice to
perform operations that need confirmation from the user, in some cases
it could be needed to offer a confirmation modal through other means.
An example is a `ButtonDropdown` which contains a remove action that
needs confirmation. In such case, we want to use the generic confirm
modal but don't want to render a button.
> feat: Added ConfirmModal to trigger user confirmation without button

- src/index.ts
The module was not exported which caused it not to be recognized in
utilizing applications
> fix: ConfirmModal was not exported

- package-lock.json
- package.json
- scripts/dev-publish.sh
- src/form/DateTimeInput/DateTimeInput.stories.tsx
- src/form/DateTimeInput/DateTimeInput.test.tsx
- src/form/DateTimeInput/DateTimeInput.tsx
- src/form/DateTimeInput/DateTimeModal/DateTimeModal.test.tsx
- src/form/DateTimeInput/DateTimeModal/DateTimeModal.tsx
- src/form/DateTimeInput/DateTimeModal/__snapshots__/DateTimeModal.test.tsx.snap
- src/form/DateTimeInput/__snapshots__/DateTimeInput.test.tsx.snap
- src/index.ts
When the user picked a date the timezone would be in the timezone that
the browser is currently in. When the user selected `28-10-2019` from
the `DateTimeInput` using the picker the value of the date would become
`2019-10-27T23:00:00.000Z`.
The `2019-10-27T23:00:00.000Z` is parsed by Spring for a `LocalDate`
as `2019-10-27`.
By using setting `react-datetime`'s `utc` property to `true` by default
the date would become: `2019-10-28T00:00:00.000Z` which is correctly
parsed.
By default the `utc` property in the `DateTimeInput` will be `true`
and this is passed to `DateTimeModal` as well.
Updated:
1. `moment` from `2.24.0` to `2.29.1`.
2. `react-datetime` from `2.16.3` to `3.04`. This changes `onFocus` to
`onOpen` as a breaking change for us. Also the name of the default
export changed to a …
> bugfix: DateTimeInput no longer uses browsers timezone.

- src/core/AsyncContent/AsyncContent.test.tsx
- src/form/TextEditor/TextEditor.stories.tsx
- src/form/TextEditor/TextEditor.test.tsx
- src/form/TextEditor/TextEditor.tsx
- src/form/TextEditor/__snapshots__/TextEditor.test.tsx.snap
- src/form/TextEditor/utils.test.ts
- src/form/TextEditor/utils.ts
Quill separates the toolbar from the allowed formats. For example it is
possible to not show the "bold" toolbar item, but to allow the ctrl-b
shortcut and pasting bold text. The `format` property defines which
formatting is actually allowed.
We did not set the `formats` for the `TextEditor` which then defaults
to allow all formats. This is unexpected, developers do not expect that
for the default toolbar we provide, that the user can for example can
paste images.
The solution is adding a `formats` property to the `TextEditor` which
by default is set to all items in the default toolbar.
This way when customising the toolbar the developer can also set the
`formats` allowing only what the end user expects.
Closes #490
> bugfix: TextEditor now longer allows all formatting such as images

- src/form/DateTimeInput/checkers.test.ts
- src/form/DateTimeInput/checkers.ts
- src/form/DateTimeInput/validators.test.ts
- src/form/DateTimeInput/validators.ts
Before the `isDateBetween` and `isDateBetweenValidator` would only
check if both the start and end date were provided. Now they work when
either are provided.
The reason that this can work is that when the start is 2020-01-01 we
and there is no end. A date of 2000-01-01 can never pass because it lies
before the start date. The same is true for when you only have an end
date and no start date.
> improvement: the isDateBetween and isDateBetweenValidator work better

- src/core/Button/Button.tsx
- src/core/Button/__snapshots__/Button.test.tsx.snap
Before the `Button` component would not accept `my`, `mt` or `mb`
bootstrap margin classes because a `<span>` is rendered which has
`display: inline;`
The reason for this is because `display: inline;` cannot use top or
bottom margins. Now it is a `display: inline-block` which does support
top and bottom margins when not rendered at `fullWidth`, and `d-block`
when rendered as `fullWidth`.
Now the `Button` is rendered as an `
Also fixed the full-width mode of the `Button` icon it misspelled:
`justify-content-start` as `justify-contents-start` and
`justify-end-start` as `justify-contents-end`.
Closes #458
> improvement: Button's now accept margin top and bottom.

- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.stories.tsx
- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.test.tsx
- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.tsx
Allow the developer to manually specify the
`optionsShouldAlwaysContainValue` value which is passed to the
`useOptions` hook.
Closes: #518
> improvement: CheckboxMultiple custom optionsShouldAlwaysContainValue

- src/form/ColorPicker/ColorPicker.stories.tsx
- src/form/ColorPicker/ColorPicker.test.tsx
- src/form/ColorPicker/ColorPicker.tsx
- src/form/IconPicker/IconPicker.stories.tsx
- src/form/IconPicker/IconPicker.test.tsx
- src/form/IconPicker/IconPicker.tsx
- src/form/ModalPicker/ModalPickerOpener/ModalPickerOpener.test.tsx
- src/form/ModalPicker/ModalPickerOpener/ModalPickerOpener.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.stories.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.test.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.tsx
- src/form/ModalPicker/single/ModalPickerSingle.stories.tsx
- src/form/ModalPicker/single/ModalPickerSingle.test.tsx
- src/form/ModalPicker/single/ModalPickerSingle.tsx
- src/form/ValuePicker/ValuePicker.stories.tsx
- src/form/ValuePicker/ValuePicker.test.tsx
- src/form/ValuePicker/ValuePicker.tsx
- src/form/ValuePicker/__snapshots__/ValuePicker.test.tsx.snap
It would be nice to have the option to display an icon in the button
that opens the picker in picker components such as the modal picker.
Added an optional icon to all picker components.
Closes #442
> improvement: icon in button for picker components

- src/form/ColorPicker/ColorPicker.stories.tsx
- src/form/ColorPicker/ColorPicker.test.tsx
- src/form/ColorPicker/ColorPicker.tsx
- src/form/ColorPicker/__snapshots__/ColorPicker.test.tsx.snap
- src/form/IconPicker/IconPicker.stories.tsx
- src/form/IconPicker/IconPicker.test.tsx
- src/form/IconPicker/IconPicker.tsx
- src/form/IconPicker/__snapshots__/IconPicker.test.tsx.snap
- src/form/ModalPicker/ModalPickerOpener/ModalPickerOpener.tsx
- src/form/ModalPicker/ModalPickerOpener/__snapshots__/ModalPickerOpener.test.tsx.snap
- src/form/ModalPicker/multiple/ModalPickerMultiple.stories.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.test.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.tsx
- src/form/ModalPicker/single/ModalPickerSingle.stories.tsx
- src/form/ModalPicker/single/ModalPickerSingle.test.tsx
- src/form/ModalPicker/single/ModalPickerSingle.tsx
- src/form/ValuePicker/ValuePicker.stories.tsx
- src/form/ValuePicker/ValuePicker.test.tsx
- src/form/ValuePicker/ValuePicker.tsx
- src/form/ValuePicker/__snapshots__/ValuePicker.test.tsx.snap
Sometimes a field is required and should work like a radio button, where
it is not possible to clear the field, you have to select at least one
option. It would be nice to be able to use all form components that way,
but for that we need an option whether to display the clear button.
Added canClear option to form components to be able to prevent users
from clearing the form element.
Closes #502
> improvement: option to hide clear button

- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.stories.tsx
- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.test.tsx
- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.tsx
- src/form/RadioGroup/RadioGroup.stories.tsx
- src/form/RadioGroup/RadioGroup.test.tsx
- src/form/RadioGroup/RadioGroup.tsx
- src/form/Select/Select.stories.tsx
- src/form/Select/Select.test.tsx
- src/form/Select/Select.tsx
- src/form/ValuePicker/ValuePicker.test.tsx
- src/form/ValuePicker/__snapshots__/ValuePicker.test.tsx.snap
When the options given to the Select component is an array with more
than 10 options, not all options are displayed.
Changed form elements that provide a selection without pagination to
display all options when an array was given as options, and a maximum of
100 options when a callback was given to fetch options.
Closes #522
> fix: select options array not displaying all options

- src/table/EpicTable/widgets/EpicDetail/EpicDetail.tsx
- src/table/EpicTable/widgets/EpicDetail/__snapshots__/EpicDetail.test.tsx.snap
When using for instance a button as last element in the detail overlay
of the EpicTable, the button sticks to the bottom of the table, even
when a margin is used.
Added padding to the bottom of the detail overlay to prevent elements to
stick to the bottom of the detail overlay and allow for margins to add
extra spacing.
Closes #514
> fix: EpicTable detail overlay padding

- src/form/Typeahead/Typeahead.scss
Users are aware of the text they just typed, so only emphasise the
predictive aspect of the query suggestion (and not what the users has
typed already, as is currently the case).
Inverted the font weight of the options to display the matching text in
normal font and the rest of the text in bold.
#517
> improvement: typeahead invert highlight styling

- docs/translations.md
- src/form/ModalPicker/multiple/ModalPickerMultiple.tsx
- src/form/ModalPicker/multiple/__snapshots__/ModalPickerMultiple.test.tsx.snap
The selection ribbon is only displayed when there is a selection in the
modal, but that causes the options to shift down when an option is
selected. It would be better if the selection ribbon could stay with a
text telling no options is selected.
Removed check that prevents selection ribbon from being displayed.
Added text to be displayed in the selection ribbon when no option is
selected.
Closes #509
> improvement: ModalPickerMultiple without selection

- src/form/useOptions.test.ts
- src/form/useOptions.ts
The default behavior for AsyncTypeahead of react-bootstrap-typeahead is
that the filter is case insensitive. I have extended this bevavior to
our own Typeaheads.
See also https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Filtering.md#casesensitive-boolean-default-false
> fix: Typeahead is now case insensitive

- src/core/InfoTooltip/InfoTooltip.stories.tsx
- src/core/InfoTooltip/InfoTooltip.test.tsx
- src/core/InfoTooltip/InfoTooltip.tsx
- src/core/InfoTooltip/__snapshots__/InfoTooltip.test.tsx.snap
- src/index.test.ts
- src/index.ts
You sometimes want to explain the use of a certain field for people that
use a form for the first time, but you don't want to display that
information all the time because it increases the size of the form and
therefore decreases its usability. A tooltip might be the perfect
solution in that case.
Added InfoTooltip compenent to display an info icon with a tooltip.
Closes #533
> feature: info tooltip

- src/form/DateTimeInput/DateTimeInput.tsx
- src/form/DateTimeInput/__snapshots__/DateTimeInput.test.tsx.snap
The autocomplete browser feature renders on top of the datepicker.
Rendering the datepicker behind the autocomplete causes the user not to
be able to use the datepicker. We should disable autocomplete for
datepicker fields.
Disabled autocomplete for DateTimeInput.
Closes #545
> fix: datepicker behind autocomplete

- src/form/Typeahead/multiple/TypeaheadMultiple.test.tsx
- src/form/Typeahead/multiple/TypeaheadMultiple.tsx
- src/form/Typeahead/multiple/__snapshots__/TypeaheadMultiple.test.tsx.snap
- src/form/Typeahead/single/TypeaheadSingle.test.tsx
- src/form/Typeahead/single/TypeaheadSingle.tsx
- src/form/Typeahead/single/__snapshots__/TypeaheadSingle.test.tsx.snap
When the options provided is an array, the options should be displayed
right away instead of waiting for user input to match any option. Not
displaying the available options right away is only useful when a
request to an API is used, to decrease the load on the API.
Changed the TypeaheadSingle and TypeaheadMultiple components to use the
Typeahead component from react-bootstrap-typeahead when the options
provided is an array to be able to display all options when the user did
not type anything in the input (yet).
Closes #544
> improvement: Typeahead should display all options

- src/form/Typeahead/single/TypeaheadSingle.test.tsx
- src/form/Typeahead/single/TypeaheadSingle.tsx
- src/form/Typeahead/single/__snapshots__/TypeaheadSingle.test.tsx.snap
Normal users find it confusing when their exact search doesn't return any result, that is because the typeahead will automatically select it and filter it out. It now only automatically selects and keeps the selected result in the search lists.
> Typeahead: keep the selected result in the search results

- src/form/NewPasswordInput/PasswordStrength/PasswordStrength.tsx
- src/form/NewPasswordInput/PasswordStrength/__snapshots__/PasswordStrength.test.tsx.snap
The NewPasswordInput displays the rules next to a check, but if the text
is too long and breaks to a new line, the text starts underneath the
icon.
Fixed alignment of password strength rules.
Closes #549
> fix: password strength rule alignment

- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.stories.tsx
- src/form/CheckboxMultipleSelect/CheckboxMultipleSelect.tsx
- src/form/CheckboxMultipleSelect/__snapshots__/CheckboxMultipleSelect.test.tsx.snap
- src/form/ValuePicker/__snapshots__/ValuePicker.test.tsx.snap
In the CheckboxMultipleSelect, the columns have a static width. When the
component is used in smaller layouts, the component overlays the
elements next to it due to the static width.
Added max-width 100% to prevent out-of-bounds display.
Removed chunking to prevent loads of whitespace when the number of
options is just over 10. The developer implementing this component is 
now responsible for the grid.
Closes #552
> fix: CheckboxMultipleSelect columns have static width

- src/core/OpenClose/OpenClose.stories.tsx
- src/core/OpenClose/OpenClose.test.tsx
- src/core/OpenClose/OpenClose.tsx
- src/core/OpenClose/_OpenClose.scss
- src/core/OpenClose/__snapshots__/OpenClose.test.tsx.snap
- src/index.test.ts
- src/index.ts
- src/main.scss
We often repeat an icon that displays whether a collapsable element is
open or closed. To prevent the usage of different icons or other
inconsistencies, we need a generic component that displays the state of
a collapsable element.
Added OpenClose component.
Closes #555
> feature: OpenClose

- src/form/DateTimeInput/DateTimeInput.scss
If dates cannot be selected, because of the condition specified in
`isDateAllowed`, this was only partly shown to the user: The cursor
became disabled and on hovering no ring was shown.
However, it is more clear if the text is also greyed out. And for the
month and year views (zoomed-out views), the disabled state was missing
altogether. This has been corrected and the disabled behaviour is now
the same across all three zoom levels (years, months, days).
> improvement: DateTime: Better indicate un-selectable days, months, years

- src/form/DateTimeInput/DateTimeInput.stories.tsx
In the DateTimeInput, the isDateAllowed does not validate the input, it
only disables clickable elements. This should be clarified as some
developers thought manually typing a date that is out of range would not
be allowed.
Added a note in the range story for the DateTimeInput component.
#561
> improvement: clarify use of isDateAllowed

- src/core/CardOpenClose/CardOpenClose.stories.tsx
- src/core/CardOpenClose/CardOpenClose.test.tsx
- src/core/CardOpenClose/CardOpenClose.tsx
- src/core/CardOpenClose/__snapshots__/CardOpenClose.test.tsx.snap
- src/index.test.ts
- src/index.ts
Now the OpenClose component is introduced, we could use that in a
collapsable card, which is often used to hide details.
Added CardOpenClose component.
Closes #558
> feature: Card with OpenClose

- README.md
The link to Verdaccio in the readme does not link to the Verdaccio
website. According to the readme, we also want contributors to use yarn
for development, which we don't. The test commands are incorrect and we
don't explain anything about storybook in the readme. Also, there should
be a banner in the readme, but the file was never included in the
repository.
Corrected the link to Verdaccio.
Changed the explanation in setup to use npm instead of yarn.
Added explanation about the use of storybook and how to run a local
environment.
Replaced non-existing banner image with 42 BV logo.
> improvement: readme

- src/form/ModalPicker/multiple/ModalPickerMultiple.stories.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.test.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.tsx
- src/form/ModalPicker/single/ModalPickerSingle.stories.tsx
- src/form/ModalPicker/single/ModalPickerSingle.test.tsx
- src/form/ModalPicker/single/ModalPickerSingle.tsx
- src/form/Typeahead/multiple/TypeaheadMultiple.stories.tsx
- src/form/Typeahead/multiple/TypeaheadMultiple.test.tsx
- src/form/Typeahead/multiple/TypeaheadMultiple.tsx
- src/form/Typeahead/multiple/__snapshots__/TypeaheadMultiple.test.tsx.snap
- src/form/Typeahead/single/TypeaheadSingle.stories.tsx
- src/form/Typeahead/single/TypeaheadSingle.test.tsx
- src/form/Typeahead/single/TypeaheadSingle.tsx
- src/form/Typeahead/single/__snapshots__/TypeaheadSingle.test.tsx.snap
Added the ability to specify the number of suggestions for
`TypeaheadSingle` and `TypeaheadMultiple`. Also added the ability to
show all predefined options matching the input. One of our applications
needs to show as much suggestions as possible, as users need to know
which values are supported.
Added the ability to change the page size of `ModalPickerMultiple` and
`ModalPickerSingle`, for some applications it is desired to have more
than 10 items per page on screen.
> feat (Typeahead, ModalPicker): Configurable page size

- docs/translations.md
- src/form/Typeahead/multiple/TypeaheadMultiple.test.tsx
- src/form/Typeahead/multiple/TypeaheadMultiple.tsx
- src/form/Typeahead/multiple/__snapshots__/TypeaheadMultiple.test.tsx.snap
- src/form/Typeahead/single/TypeaheadSingle.test.tsx
- src/form/Typeahead/single/TypeaheadSingle.tsx
- src/form/Typeahead/single/__snapshots__/TypeaheadSingle.test.tsx.snap
If a large set of items is passed (or `pageSize` is higher than 100),
ReactStrap will add a fallback pagination to the dropdown to ensure the
DOM performance stays optimal.
The text of this pagination button was not configurable. This has now
been resolved.
> feat(Typeahead): Allow customizing the reactstrap pagination text

- src/core/CardOpenClose/CardOpenClose.stories.tsx
- src/core/CardOpenClose/CardOpenClose.test.tsx
- src/core/CardOpenClose/CardOpenClose.tsx
- src/core/CardOpenClose/__snapshots__/CardOpenClose.test.tsx.snap
- src/core/Debug/Debug.test.tsx
- src/core/Debug/Debug.tsx
- src/core/Debug/__snapshots__/Debug.test.tsx.snap
The content property should have been called children instead. This
makes for a better API.
We should deprecate content but not remove it and wait until 4.0.0 to
remove it.
Added children prop to replace the content prop in the next major
version.
Closes #575
> improvement: CardOpenClose rename content to children

- src/core/AsyncActionButton/AsyncActionButton.stories.tsx
- src/core/AsyncActionButton/AsyncActionButton.test.tsx
- src/core/AsyncActionButton/AsyncActionButton.tsx
- src/core/AsyncActionButton/__snapshots__/AsyncActionButton.test.tsx.snap
- src/form/story-utils.tsx
- src/index.test.ts
- src/index.ts
I want to have a button that triggers a request that should only be
triggered once at a time, so the button should be disabled while the
request is still pending and it should display a loading state.
Added the AsyncActionButton component.
Closes #580
> feature: Async action button

- src/table/EpicTable/helpers/GooeyCenter/GooeyCenter.tsx
We have a case where the space the table has is not enough to fit all
columns, but when the sidebar is minified, there is enough space to fit
all columns. When the sidebar is opened again, the table is not resized
until the user moves the mouse over the EpicTable. We would like to have
a custom trigger we can call to force the table to resize.
Added event listener to listen to custom resizeEpicTables event as well
as window resize.
Closes #608
> feature: EpicTable resize trigger

- src/form/Select/Select.tsx
- src/form/Select/__snapshots__/Select.test.tsx.snap
The placeholder you define cannot be disabled. If you don't specify a
placeholder, you still have an empty value you can select even if you
don't want to. It would help if Select would not display an empty option
if the placeholder is empty.
Added check if placeholder is empty to prevent an empty option.
Closes #616
> improvement: select without placeholder

- src/core/Pagination/Pagination.scss
- src/core/Pagination/Pagination.test.tsx
- src/core/Pagination/Pagination.tsx
- src/core/Pagination/__snapshots__/Pagination.test.tsx.snap
Currently, the pagination component could change position when it is
centered on a page depending on what page you are on. This should be
changed to always display a static amount of buttons, so the position of
the pagination component does not change when navigating between pages.
Changed pagination to always display the same amount of buttons.
Closes #604
> improvement: Pagination static number of items

- src/index.test.ts
- src/index.ts
- src/table/CrudTable/CrudTable.stories.tsx
- src/table/CrudTable/CrudTable.test.tsx
- src/table/CrudTable/CrudTable.tsx
- src/table/CrudTable/__snapshots__/CrudTable.test.tsx.snap
- src/table/CrudTable/components/CrudHeader/CrudHeader.test.tsx
- src/table/CrudTable/components/CrudHeader/CrudHeader.tsx
- src/table/CrudTable/components/CrudHeader/__snapshots__/CrudHeader.test.tsx.snap
- src/table/EpicTable/cells/EpicCell/EpicCell.test.tsx
- src/table/EpicTable/cells/EpicCell/EpicCell.tsx
- src/table/EpicTable/cells/EpicCell/__snapshots__/EpicCell.test.tsx.snap
- src/table/EpicTable/cells/EpicHeader/EpicHeader.tsx
We are using the EpicTable a lot for our entity listings and it would be
a lot easier if there is a component that simplifies the EpicTable for
that purpose.
Added CrudTable component which wraps the EpicTable to make it easier to
display a table with create/edit/detail view and pagination.
Added CrudHeader component to simplify the display of a header with
sort and search functionality.
Closes #605
> feature: CrudTable

- src/core/AsyncContent/AsyncContent.stories.tsx
- src/core/AsyncList/AsyncList.stories.tsx
- src/core/AsyncPage/AsyncPage.stories.tsx
In the storybook, in all AsyncContent, AsyncList and AsyncPage stories,
an error is displayed: No QueryClient set, use QueryClientProvider to
set one.
Added decorator to wrap async stories in QueryClientProvider.
Closes #624
> fix: async stories no query client error

- src/core/EpicPagination/EpicPagination.scss
- src/core/EpicPagination/EpicPagination.stories.tsx
- src/core/EpicPagination/EpicPagination.test.tsx
- src/core/EpicPagination/EpicPagination.tsx
- src/core/EpicPagination/__snapshots__/EpicPagination.test.tsx.snap
- src/core/Pagination/Pagination.scss
- src/core/Pagination/Pagination.tsx
- src/main.scss
Instead of using ellipsis and always display first and last page
numbers, some people prefer the active page to always be in the middle
and display the total number of records.
Added EpicPagination component that works similar to the existing
Pagination component but has a different look and feel.
> feature: epic pagination

- src/form/NewPasswordInput/PasswordStrength/useMeterWidth/useMeterWidth.test.ts
- src/hooks/useHover/useHover.test.tsx
Hooks should always be tested using renderHook.
Added renderHook to useHover and useMeterWidth testing.
> improvement: testing custom hooks

- src/index.test.ts
- src/index.ts
It might be useful to expose ModalPicker to allow developers to build
their own ModalPicker variant with more flexibility.
Exposed ModalPicker.
Closes #626
> improvement: expose ModalPicker

- src/core/ConfirmButton/ConfirmButton.tsx
The ConfirmButton allows a disabled property as it is an extension to
the Button component, but it doesn't pass the property to the Button.
Changed ConfirmButton to pass disabled property to Button.
Closes #658
> improvement: ConfirmButton disabled property

- docs/translations.md
- package-lock.json
- package.json
- src/form/DateTimeInput/DateTimeInput.scss
- src/form/DateTimeInput/DateTimeInput.stories.tsx
- src/form/DateTimeInput/DateTimeInput.test.tsx
- src/form/DateTimeInput/DateTimeInput.tsx
- src/form/DateTimeInput/DateTimeModal/DateTimeModal.test.tsx
- src/form/DateTimeInput/DateTimeModal/DateTimeModal.tsx
- src/form/DateTimeInput/DateTimeModal/__snapshots__/DateTimeModal.test.tsx.snap
- src/form/DateTimeInput/__snapshots__/DateTimeInput.test.tsx.snap
- src/form/DateTimeInput/utils.test.tsx
- src/form/DateTimeInput/utils.ts
- src/form/DateTimeInput/validators.test.ts
- src/form/DateTimeInput/validators.ts
- src/form/FormError/FormError.test.tsx
- src/form/FormExample.stories.tsx
- src/form/Input/Input.stories.tsx
- src/form/Input/Input.test.tsx
- src/form/Input/Input.tsx
- src/form/Input/__snapshots__/Input.test.tsx.snap
- src/form/NewPasswordInput/NewPasswordInput.stories.tsx
- src/form/withJarb/withJarb.test.tsx
- storybook/preview.js
Too many new issues arose with the migration to react-datepicker. The input blurred too fast, the input did not focus at all with keyboard navigation, final form continuously in validating state.
This reverts commits 31e98ab5b74d3759b4c2c09bfc3a7622fdded375 and e711736b6d41587ece90391b48557457fd5a4973.
Closes #668
> Revert "fix: date validators" and "improvement: replace React Datetime dependency"

- package-lock.json
- package.json
- src/form/ImageUpload/ImageUpload.stories.tsx
- src/form/ImageUpload/utils.ts
When uploading an image, we get a console error Buffer is not defined.
Added buffer to optional peer dependencies for ImageUpload component.
> fix: image upload buffer not defined

- scripts/dev-publish.sh
- read-call updated to use -r flag. Removed -p flag.
- Removed string-indexing in case.
- Removed double-bracket syntax.
- Removed $() from until-statement.
Note that almost all of these changes can be discarded by using #!/bin/bash or similar.
> Updated script for POSIX compliance

- docs/translations.md
- src/core/EpicPagination/EpicPagination.scss
- src/core/EpicPagination/EpicPagination.stories.tsx
- src/core/EpicPagination/EpicPagination.test.tsx
- src/core/EpicPagination/EpicPagination.tsx
- src/core/EpicPagination/__snapshots__/EpicPagination.test.tsx.snap
- src/core/Pagination/Pagination.scss
- src/core/Pagination/Pagination.stories.tsx
- src/core/Pagination/Pagination.test.tsx
- src/core/Pagination/Pagination.tsx
- src/core/Pagination/__snapshots__/Pagination.test.tsx.snap
- src/form/ModalPicker/ModalPicker.tsx
The EpicPagination displays the total number of elements. I would like to see that in the Pagination component as well.
Added total elements to Pagination component.
Changed total elements in EpicPagination to be translatable string. Added possibility to hide total elements in Pagination and EpicPagination.
Closes #687
> improvement: add total elements counter to Pagination

- src/core/ConfirmButton/ConfirmButton.tsx
- src/core/ConfirmButton/__snapshots__/ConfirmButton.test.tsx.snap
The ConfirmButton has a wrapping div (default display inline), that is unnecessary and causes layout problems.
Changed wrapping div to react fragment.
> improvement: remove wrapping div from ConfirmButton

- src/core/Pagination/Pagination.tsx
- src/core/Pagination/__snapshots__/Pagination.test.tsx.snap
- src/form/ModalPicker/__snapshots__/ModalPicker.test.tsx.snap
When used in a form, the pagination triggers a form submit.
Changed pagination links to be buttons with type button instead of the 
default submit.
Closes #702
> fix: pagination clicking page triggers form submit

- src/core/Button/Button.tsx
- src/form/ModalPicker/ModalPickerOpener/ModalPickerOpener.tsx
- src/form/ModalPicker/multiple/ModalPickerMultiple.tsx
- src/form/ModalPicker/single/ModalPickerSingle.tsx
When the button in ModalPicker components is clicked, the event is propagated, causing parent elements onClick to trigger as well.
Added event preventDefault to ModalPicker components.
> fix: ModalPicker button onClick propagation

- src/form/Input/Input.test.tsx
- src/form/Input/Input.tsx
- src/form/Input/__snapshots__/Input.test.tsx.snap
- src/form/NewPasswordInput/NewPasswordInput.tsx
- src/form/withField/__snapshots__/withField.test.tsx.snap
- src/form/withJarb/__snapshots__/withJarb.test.tsx.snap
- src/table/EpicTable/cells/EpicForm/__snapshots__/EpicForm.test.tsx.snap
I want to set autocomplete on an input, but that's not an allowed property of Input yet.
Added support for HTML attributes on Input element.
> improvement: HTML attributes on Input
